version: 2
services:

  demoservice-lb:
    image: rancher/load-balancer-service
    ports:
      - ${host_port}:8000/tcp
    links:
      - demoservice-web:server

  demoservice-web:
    image: canonicalwebteam/demoservice
    command: ./start_web.sh
    privileged: true
    links:
      - demoservice-db:demoservice-db
      - demoservice-rabbit:demoservice-rabbit
    external_links:
      - ${logstash_service}:logstash
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "GITHUB_TOKEN=${github_token}"
      - "GITHUB_WEBHOOK_SECRET=${github_token}"
      - "LOGSTASH_HOST=logstash.rancher.internal"
      - "LOGSTASH_PORT=5000"
      - "LOG_LEVEL=DEBUG"
      - "POSTGRES_HOST=demoservice-db"
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "RABBITMQ_HOST=demoservice-rabbit"
      - "SECRET_KEY=${secret_key}"

  demoservice-worker:
    image: canonicalwebteam/demoservice
    command: ./start_celery.sh
    privileged: true
    links:
      - demoservice-db:demoservice-db
      - demoservice-rabbit:demoservice-rabbit
    external_links:
      - ${logstash_service}:logstash
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/run.demo.haus-demos:/srv/run.demo.haus-demos
    environment:
      - "GITHUB_TOKEN=${github_token}"
      - "LOGSTASH_HOST=logstash.rancher.internal"
      - "LOGSTASH_PORT=5000"
      - "LOG_LEVEL=DEBUG"
      - "POSTGRES_HOST=demoservice-db"
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASS=postgres"
      - "RABBITMQ_HOST=demoservice-rabbit"
      - "SECRET_KEY=${secret_key}"
      - "DEMO_OPT_SECRET_KEY=${demo_opt_secret_key}"

  demoservice-rabbit:
    hostname: demoservice-rabbit
    image: rabbitmq:3.6
    environment:
     - "RABBITMQ_DEFAULT_USER=guest"
     - "RABBITMQ_DEFAULT_PASS=guest"

  demoservice-db:
    hostname: demoservice-db
    image: postgres:9.4
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=postgres"
